### ISSUE TITLE
Map places markers in wrong locations

### ISSUE THREAD

**Issue by ctoujoma** [LibrePhotos/librephotos#1159]
# 🐛 Bug Report

* [X] 📁 I've Included a ZIP file containing my librephotos `log` files -> [logs.zip](https://github.com/LibrePhotos/librephotos/files/14254028/logs.zip)
* [ ] ❌ I have looked for similar issues (including closed ones)
* [X] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:

The map in the 'Places' section shows the markers in wrong locations. On the photo details the GPS location is showed properly and also places list in the 'Places' section, under the map

## 🔁 How can we reproduce it:

Not sure, but i guess just putting a bunch of photos with geolocalitzation data on some folder and doing a full scan,
i tested with different map providers, on the GUI settings

![image](https://github.com/LibrePhotos/librephotos/assets/11389323/40f81b00-8efd-4884-be26-e2ecdcb91fe2)

## Please provide additional information:
- 💻 Operating system: Debian 12
- ⚙ Architecture (x86 or ARM):  ARM
- 🔢 Librephotos version: 2024w05
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): docker-compose
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: 
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.):  Local File System (ext4)
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.):

**Comment by sickelap** [comment]
@ctoujoma which map provide you are using?

**Comment by ctoujoma** [comment]
@sickelap Mapbox, i have an API key

**Comment by ctoujoma** [comment]
If i switch to other map providers it shows the same, i have the feeling its not really changing the map provider..
I've restarted server and same result

**Comment by sickelap** [comment]
This is fixed now. It appears Mapbox and Photon parsing was broken. I guess you have tried those, and it did not work.
Other providers should have worked.

**Comment by ctoujoma** [comment]
Hi @sickelap,
Im afraid in my case is still not fixed..
![image](https://github.com/LibrePhotos/librephotos/assets/11389323/ac3d2781-896d-4ab7-93b1-c31fb5a0166d)

Also, im almost sure i've tried all map providers, maybe the settings are not applying correctly.

I've updated (im on 2024w09),
Maybe i need a full rescan? Is there a way to just rescan for geolocation info?

**Comment by sickelap** [comment]
@ctoujoma It has not been released yet. You have a choice of either using the latest dev branch or waiting for the next release

**Comment by ctoujoma** [comment]
oops, ok
didnt know,
thx!
