### ISSUE TITLE
no photos show up under places

### ISSUE THREAD

**Issue by phynias** [LibrePhotos/librephotos#305]
## 🐛 Bug Report

* [ x] I am including my log files in zip format.
* [x ] I have looked for similar issues among all the former issues including closed ones.

### What architecture is LibrePhotos running on:
x64

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
Docker version 20.10.3, build 48d30b5

### Are you running LibrePhotos on a virtual machine if so please list:
-

### How is you picture library mounted on the host (or in the virtual machine):
Local file system

### Description of issue:
photos all have location data in the info but when you go to album->places it shows 0 photos

#### Additional Information:

* Include a ZIP file containing your `log` files.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by phynias** [comment]
[logs.zip](https://github.com/LibrePhotos/librephotos/files/6910078/logs.zip)

**Comment by trowj** [comment]
Do you have a MapBox key defined in your `.env` file?

**Comment by gmensching** [comment]
> Do you have a MapBox key defined in your `.env` file?

I'm having the same issue and I have a MapBox key defined in my .env file.

**Comment by phynias** [comment]
> Do you have a MapBox key defined in your `.env` file?

yes.

**Comment by n8herring** [comment]
I have the same issue. Same version.  Using Local File System and DO have MapBox key in .env

Photos all show location information and small map in info 'tab' from Lightbox but none show in places. 

Not sure if it is relevant; however, in database the json field for geo is empty for each but the lat lon fields are populated.

**Comment by witchcraftsman** [comment]
Spent some time to investigate:
Weird piece of code in photo.py, _geolocate_mapbox() -
```
        old_gps_lat = self.exif_gps_lat
        old_gps_lon = self.exif_gps_lon            
        self._extract_gps_from_exif()
        # Skip if it hasn't changed or is null
        if(not self.exif_gps_lat or not self.exif_gps_lon):
            return
        if (old_gps_lat == self.exif_gps_lat and old_gps_lon == self.exif_gps_lon):
            return
```
Last IF always gets RETURN, so gps lat and lon are already populated and 'not changed'
Commenting those 2 lines of code makes calling Mapbox happen so I get "self.geolocation_json" filled with data, but that doesn't fix that whole thing. 
So I guess it's WIP

**Comment by derneuere** [comment]
self._extract_gps_from_exif() should change the values from self.exif_gps_lat and self.exif_gps_lon. That way, we should only update when a value has changed.

**Comment by derneuere** [comment]
I think I found the error. I pushed the code. A new image should be available in an hour.

**Comment by phynias** [comment]
grabbed the latest docker images and ran a scan. still nothing in places.

**Comment by phynias** [comment]
i spoke too soon. just checked it again and there are now photos showing up!!

**Comment by gmensching** [comment]
I did a pull this morning and ran a scan.  I'm still not seeing anything.  It's probably been 4 hours.  How long does it typically take?  I don't see anything in the logs.

**Comment by derneuere** [comment]
It should show up after the scan is finished.

**Comment by gmensching** [comment]
> It should show up after the scan is finished.

I guess I must have a different issue then.  I'll post on Discord.

**Comment by n8herring** [comment]
Since I was still in a testing mode and had only 13 images in my system I decided to start over using the latest images and now no gps data seems to be populating.  In fact I doesn't look like I am getting ANY exif data now and the scan seems to hang after 7 images that previously scanned fine.  

The rqworker log just stops here:
ERROR:ownphotos:job 28d33c07-a8b5-4372-a5e5-3cfccddc6a3e: could not load image /data/IMG_3513.jpg. reason: 'NoneType' object has no attribute 'location'
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 109, in handle_new_image
    photo._geolocate_mapbox(False)
  File "/code/api/models/photo.py", line 307, in _geolocate_mapbox
    if album_date.location and len(album_date.location) > 0:
AttributeError: 'NoneType' object has no attribute 'location'

**Comment by n8herring** [comment]
I am adding this comment to this thread since it seems to have started when I attempted to rebuild and test places

**Comment by gmensching** [comment]
> Since I was still in a testing mode and had only 13 images in my system I decided to start over using the latest images and now no gps data seems to be populating. In fact I doesn't look like I am getting ANY exif data now and the scan seems to hang after 7 images that previously scanned fine.
> 
> The rqworker log just stops here:
> ERROR:ownphotos:job 28d33c07-a8b5-4372-a5e5-3cfccddc6a3e: could not load image /data/IMG_3513.jpg. reason: 'NoneType' object has no attribute 'location'
> Traceback (most recent call last):
> File "/code/api/directory_watcher.py", line 109, in handle_new_image
> photo._geolocate_mapbox(False)
> File "/code/api/models/photo.py", line 307, in _geolocate_mapbox
> if album_date.location and len(album_date.location) > 0:
> AttributeError: 'NoneType' object has no attribute 'location'

I'm getting the same logs it looks like.  Do we need to open a new issue since this is closed?
![image](https://user-images.githubusercontent.com/87952793/129662298-eaa08444-a214-4a33-8286-2dcbd9fc1f43.png)

**Comment by derneuere** [comment]
I changed the order of scanning yesterday. This should fix this bug, I think. Not sure why I can't recreate it, though.

**Comment by gmensching** [comment]
> I changed the order of scanning yesterday. This should fix this bug, I think. Not sure why I can't recreate it, though.

I just did another pull and looks like the same issue still.  Let me know if there is any additional information I can provide that would be helpful.  Would any attributes of this specific photo help?  Thank you for the help on this.

![image](https://user-images.githubusercontent.com/87952793/129726961-2a421918-04ea-4828-8ff0-30766f9877a4.png)

**Comment by n8herring** [comment]
I started the day with the three docker-compose commands down, pull ups -d so I should have the latest.

I am no longer seeing the 'no attribute' error but still have nothing showing under Places.  

I'd be happy to try to help gather information.  Years ago I was a developer and Python isn't my forte but a straightforward language.

I know my way around it enough to troubleshoot and of if nothing else drop in the util.logger.info function along the way to track down information.  Would this be of use and if so which .py files should I be evaluating?  

Another observation:
I'm also seeing the scan hang after on every 2-5 NEW photos as I add them and test.  It seems to move well through the ones it has previously scanned and then just sits (or so it appears in the admin area) after taking a bite of the new ones.  It sees the proper number of photos in the data folder (mapped to host filesystem) (y) in the progress bar's x/y label. 

I don't see any errors in the rqworker.log file and after about 5-10 minutes of no progress I can get things moving again by restarting the backend container (I also remove the job from the admin area as well) and then starting up another scan and it moves a little further on the new photos again before hanging.

I'm testing with a mix of jpg and dng files (ranging in size from 12mpx to 36mpx) and it does not appear to be related to the filetype or image size as I can drop in a batch of either and it will hang as well as hanging on a mix.  I am using the database to watch exif_timestamp to know which ones it has done and which it has not but I'm not sure of a way to find out the last one done or the one it stops on - advice on where to drop some debug lines and I'll add more info once I know more.

Thanks
n8

**Comment by derneuere** [comment]
> > I changed the order of scanning yesterday. This should fix this bug, I think. Not sure why I can't recreate it, though.
> 
> I just did another pull and looks like the same issue still. Let me know if there is any additional information I can provide that would be helpful. Would any attributes of this specific photo help? Thank you for the help on this.
> 
> ![image](https://user-images.githubusercontent.com/87952793/129726961-2a421918-04ea-4828-8ff0-30766f9877a4.png)

This looks like an old build. Please do a docker-compose down

**Comment by derneuere** [comment]
@n8herring 
Alright, this is sounds like a different issue. It reminds me of #167 

The main file you should be looking at is the "ownphotos.log", there should be an error message if an error occurs. It also logs the current progress.

**Comment by gmensching** [comment]
> > > I changed the order of scanning yesterday. This should fix this bug, I think. Not sure why I can't recreate it, though.
> > 
> > 
> > I just did another pull and looks like the same issue still. Let me know if there is any additional information I can provide that would be helpful. Would any attributes of this specific photo help? Thank you for the help on this.
> > ![image](https://user-images.githubusercontent.com/87952793/129726961-2a421918-04ea-4828-8ff0-30766f9877a4.png)
> 
> This looks like an old build. Please do a docker-compose down

Ok I did another pull.  The error is gone from the logs now.  If I got to albums / places I see zero pictures.  This is the first time places has started to work for me so I'm not sure if this is what to expect.  Maybe I need to create an album but I was under the impression this would generate.  

![image](https://user-images.githubusercontent.com/87952793/129809541-97a38596-e1b2-4d6c-a60a-28f9cbde98ab.png)

I can however search and places come up and the pictures for those locations do as well.

![image](https://user-images.githubusercontent.com/87952793/129810400-04575a8e-04ed-409b-b536-935cd28c7963.png)

I do also get the location in the picture information now.

![image](https://user-images.githubusercontent.com/87952793/129809469-570c398b-e5fb-41e2-8fde-02d1ea89b92b.png)

One thing to note is another picture that has the location information but is getting a date error is missing the location in the picture information but it does come up in the search.  

![image](https://user-images.githubusercontent.com/87952793/129810758-b412b657-d7f0-48bf-913c-8d94b8c428a4.png)

Thank you for the help.  I appreciate it.

**Comment by n8herring** [comment]
@derneuere 
In order to (I think) rule out Issue 167 as you mentioned above I created a Debian 9 server for a clean test.  I allowed the container startup to create the folders (I note that it runs as root (UID 0) and that lines up with the folders being owned by root in Debian.  I still have the hanging issue on scanning the directory.  Here are the last few entries in the ownphotos.log file for 3 times it has stopped processing:

-----  First stop ended with this line (I should have grabbed more lines)
2021-08-17 11:00:35,931 : api_util.py : get_location_clusters : 260 : INFO : location clustering took 0.05 seconds


----- Second stop ended with these lines (after removing job in admin area and then restarting the backend container followed by initiating a new scan from settings.
2021-08-18 16:10:46,765 : photo.py : _generate_captions : 143 : INFO : generated places365 captions for image /protected_media/thumbnails_big/6318b48c7fe3ac9fdaadfeb217d8fe5f1.webp.
2021-08-18 16:11:40,440 : photo.py : _generate_clip_embeddings : 117 : INFO : generated clip embeddings for image /protected_media/thumbnails_big/7febea140569f1bd382649692af64d3e1.webp.
2021-08-18 16:11:41,650 : util.py : mapbox_reverse_geocode : 97 : INFO : mapbox returned status 200.
2021-08-18 16:11:42,037 : directory_watcher.py : handle_new_image : 89 : INFO : job 797834bd-7d73-4c65-8da4-da4599df83ca: handling image /data/IMG_0224.jpg
2021-08-18 16:11:43,969 : photo.py : _generate_captions : 143 : INFO : generated places365 captions for image /protected_media/thumbnails_big/acd8d082d18696a085f36586d574ddbb1.webp.
2021-08-18 16:14:22,431 : views.py : list : 515 : INFO : querying & serializing took 0.60 seconds


----- Third stop ended with these lines (again after remove job, restart backend and click scan button in settings)
2021-08-19 14:38:41,065 : directory_watcher.py : handle_new_image : 89 : INFO : job 2593698e-153d-4a3d-98c0-d8fcc6bde250: handling image /data/IMG_3513.jpg
2021-08-19 14:38:43,538 : photo.py : _generate_captions : 143 : INFO : generated places365 captions for image /protected_media/thumbnails_big/dbd2bd73b451e048584f3082589e2ca71.webp.


----- Place Not Populating Issue


WRT Places not populating.  I am still not seeing anything appear there.

Unlike gmensching, I do NOT get any results if I search.

I DO see the location displayed when I drill into the Lightbox and look under the info.  I see GPS lat/lon in the database but the geo...json field is just {} if that makes any difference.

I'm happy to try anything you need or help in any way I can!

Thanks for all the work you put into this great project!
n8

**Comment by n8herring** [comment]
@derneuere
(Posting this in #308)
I have had issues with getting photos to all scan (I had first added it as part of the reply to another issue (no photos show up under places #305) as scanning would never complete.  I will also update #305 to keep things together there.

I have tried remove as many layers as possible in the docker setup by moving the test to a Debian9 VM (set with 4vcpu 4GB RAM) as opposed to MacOS which is just using a hidden Linux VM.

NOW I can see an error in the ownphotos.log where before I could not.  It appears to just suck all of the memory and the whole VM becomes unresponsive...


---- HERE IS THE COMPLETE LOG FROM A CLEAN TRY ----

021-08-30 12:13:17,086 : views.py : list : 515 : INFO : querying & serializing took 0.01 seconds
2021-08-30 12:13:27,271 : serializers.py : update : 720 : INFO : Updated scan directory for user /data
2021-08-30 12:13:27,273 : serializers.py : update : 726 : INFO : Updated confidence for user 0.1
2021-08-30 12:13:27,274 : serializers.py : update : 736 : INFO : Updated semantic_search_topk for user 0
2021-08-30 12:13:27,275 : serializers.py : update : 742 : INFO : Updated favorite_min_rating for user 4
2021-08-30 12:13:43,409 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_3513.jpg
2021-08-30 12:13:45,702 : photo.py : _generate_captions : 143 : INFO : generated places365 captions for image /protected_media/thumbnails_big/dbd2bd73b451e048584f3082589e2ca71.webp.
2021-08-30 12:13:52,303 : photo.py : _generate_clip_embeddings : 117 : INFO : generated clip embeddings for image /protected_media/thumbnails_big/dbd2bd73b451e048584f3082589e2ca71.webp.
2021-08-30 12:13:53,592 : util.py : mapbox_reverse_geocode : 97 : INFO : mapbox returned status 200.
2021-08-30 12:13:54,889 : photo.py : _extract_faces : 362 : INFO : image dbd2bd73b451e048584f3082589e2ca71: 2 face(s) saved
2021-08-30 12:13:54,891 : directory_watcher.py : handle_new_image : 114 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: image processed: /data/IMG_3513.jpg, elapsed: 11.455016
2021-08-30 12:13:54,906 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_3065.jpg
2021-08-30 12:13:56,146 : photo.py : _generate_captions : 143 : INFO : generated places365 captions for image /protected_media/thumbnails_big/13f966e0d6ab83b3657878097a3ce1bc1.webp.
2021-08-30 12:14:03,017 : photo.py : _generate_clip_embeddings : 117 : INFO : generated clip embeddings for image /protected_media/thumbnails_big/13f966e0d6ab83b3657878097a3ce1bc1.webp.
2021-08-30 12:14:03,049 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_3065.jpg. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 109, in handle_new_image
    photo._extract_date_time_from_exif(True)
  File "/code/api/models/photo.py", line 211, in _extract_date_time_from_exif
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:14:03,240 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_9411.HEIC.heif
2021-08-30 12:14:05,848 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_9411.HEIC.heif. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:14:05,913 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_2143.HEIC.heif
2021-08-30 12:14:08,147 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_2143.HEIC.heif. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:14:08,202 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/567712203.458368public.jpg
2021-08-30 12:14:08,713 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/567712203.458368public.jpg. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:14:08,836 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_2386.heic
2021-08-30 12:14:11,886 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_2386.heic. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:14:11,952 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_8176.jpg
2021-08-30 12:14:12,717 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_8176.jpg. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:14:12,778 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_5830.heic
2021-08-30 12:14:14,758 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_5830.heic. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:14:14,826 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_7527.heic
2021-08-30 12:14:17,863 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_7527.heic. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:14:17,922 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_0224.jpg
2021-08-30 12:14:18,552 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_0224.jpg. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:14:18,627 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_5896.heic
2021-08-30 12:14:21,493 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_5896.heic. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:14:21,512 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/WP_20151218_13_30_28_Raw__highres.dng
2021-08-30 12:19:54,456 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_3297.heic
2021-08-30 12:19:58,838 : photo.py : _generate_captions : 143 : INFO : generated places365 captions for image /protected_media/thumbnails_big/c8c4c21ce392750f27807efc3e098bcd1.webp.
2021-08-30 12:20:05,393 : photo.py : _generate_clip_embeddings : 117 : INFO : generated clip embeddings for image /protected_media/thumbnails_big/c8c4c21ce392750f27807efc3e098bcd1.webp.
2021-08-30 12:20:06,945 : util.py : mapbox_reverse_geocode : 97 : INFO : mapbox returned status 200.
2021-08-30 12:20:08,988 : photo.py : _extract_faces : 362 : INFO : image c8c4c21ce392750f27807efc3e098bcd1: 1 face(s) saved
2021-08-30 12:20:08,990 : directory_watcher.py : handle_new_image : 114 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: image processed: /data/IMG_3297.heic, elapsed: 14.474443
2021-08-30 12:20:09,022 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/WP_20171127_21_17_10_Pro__highres.jpg
2021-08-30 12:20:10,789 : photo.py : _generate_captions : 143 : INFO : generated places365 captions for image /protected_media/thumbnails_big/576e7b15b9ca9a795945f70f2d6336c31.webp.
2021-08-30 12:20:16,222 : photo.py : _generate_clip_embeddings : 117 : INFO : generated clip embeddings for image /protected_media/thumbnails_big/576e7b15b9ca9a795945f70f2d6336c31.webp.
2021-08-30 12:20:17,072 : util.py : mapbox_reverse_geocode : 97 : INFO : mapbox returned status 200.
2021-08-30 12:20:19,459 : photo.py : _extract_faces : 362 : INFO : image 576e7b15b9ca9a795945f70f2d6336c31: 1 face(s) saved
2021-08-30 12:20:19,460 : directory_watcher.py : handle_new_image : 114 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: image processed: /data/WP_20171127_21_17_10_Pro__highres.jpg, elapsed: 10.394164
2021-08-30 12:20:19,516 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_6338.heic
2021-08-30 12:20:22,407 : photo.py : _generate_captions : 143 : INFO : generated places365 captions for image /protected_media/thumbnails_big/a7569195075a165f4813dc3e6dc2b93a1.webp.
2021-08-30 12:20:27,582 : photo.py : _generate_clip_embeddings : 117 : INFO : generated clip embeddings for image /protected_media/thumbnails_big/a7569195075a165f4813dc3e6dc2b93a1.webp.
2021-08-30 12:20:28,813 : util.py : mapbox_reverse_geocode : 97 : INFO : mapbox returned status 200.
2021-08-30 12:20:29,922 : photo.py : _extract_faces : 362 : INFO : image a7569195075a165f4813dc3e6dc2b93a1: 1 face(s) saved
2021-08-30 12:20:29,923 : directory_watcher.py : handle_new_image : 114 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: image processed: /data/IMG_6338.heic, elapsed: 10.397034
2021-08-30 12:20:29,941 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/WP_20160823_19_25_11_Raw__highres.dng
2021-08-30 12:21:37,015 : photo.py : _generate_captions : 143 : INFO : generated places365 captions for image /protected_media/thumbnails_big/6e3aa849ab5f116973f9220a42f956ff1.webp.
2021-08-30 12:21:43,208 : photo.py : _generate_clip_embeddings : 117 : INFO : generated clip embeddings for image /protected_media/thumbnails_big/6e3aa849ab5f116973f9220a42f956ff1.webp.
2021-08-30 12:21:46,049 : directory_watcher.py : handle_new_image : 114 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: image processed: /data/WP_20160823_19_25_11_Raw__highres.dng, elapsed: 75.926134
2021-08-30 12:21:46,087 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_0404.jpg
2021-08-30 12:21:46,866 : photo.py : _generate_captions : 143 : INFO : generated places365 captions for image /protected_media/thumbnails_big/4f4e6ff4bc394df5d5222216e3fb28401.webp.
2021-08-30 12:21:52,186 : photo.py : _generate_clip_embeddings : 117 : INFO : generated clip embeddings for image /protected_media/thumbnails_big/4f4e6ff4bc394df5d5222216e3fb28401.webp.
2021-08-30 12:21:53,849 : photo.py : _extract_faces : 362 : INFO : image 4f4e6ff4bc394df5d5222216e3fb28401: 1 face(s) saved
2021-08-30 12:21:53,850 : directory_watcher.py : handle_new_image : 114 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: image processed: /data/IMG_0404.jpg, elapsed: 7.750198
2021-08-30 12:21:53,935 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_5584.heic
2021-08-30 12:21:56,280 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_5584.heic. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:21:56,340 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/SarverHerringWedding-72.jpg
2021-08-30 12:21:56,946 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/SarverHerringWedding-72.jpg. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:21:57,011 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_6369.heic
2021-08-30 12:21:58,906 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_6369.heic. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:21:58,930 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/SarverHerringWedding-230.jpg
2021-08-30 12:21:59,486 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/SarverHerringWedding-230.jpg. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:21:59,561 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_0433.jpeg
2021-08-30 12:22:00,267 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_0433.jpeg. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:22:00,299 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_3516.jpg
2021-08-30 12:22:01,211 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_3516.jpg. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:22:01,232 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_6670.jpg
2021-08-30 12:22:01,534 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_6670.jpg. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:22:01,614 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_5720.heic
2021-08-30 12:22:03,791 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_5720.heic. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:22:03,819 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_0372.jpg
2021-08-30 12:22:04,380 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_0372.jpg. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:22:04,417 : directory_watcher.py : handle_new_image : 89 : INFO : job 39b9ca47-340a-4927-8dff-8692774c8db8: handling image /data/IMG_3310.jpg
2021-08-30 12:22:05,177 : directory_watcher.py : handle_new_image : 134 : ERROR : job 39b9ca47-340a-4927-8dff-8692774c8db8: could not load image /data/IMG_3310.jpg. reason: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 106, in handle_new_image
    photo._calculate_aspect_ratio(False)
  File "/code/api/models/photo.py", line 200, in _calculate_aspect_ratio
    with exiftool.ExifTool() as et:
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 410, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 381, in start
    raise oe
  File "/usr/local/lib/python3.9/dist-packages/exiftool/exiftool.py", line 372, in start
    self._process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
2021-08-30 12:23:56,749 : api_util.py : get_location_clusters : 260 : INFO : location clustering took 0.01 seconds

**Comment by n8herring** [comment]
Ahhh. I should have also noted that in this test I allowed the docker image to create the host folder for the volume mapping fo the /data map.  It created it with root ownership and then I moved the photos to the folder instead of mapping to an existing folder.

**Comment by n8herring** [comment]
this was done with a docker image pulled at approx 3:30PM UTC on 30-AUG-2021

**Comment by n8herring** [comment]
Update: added more RAM to VM in 4GB increments, cleared out all of the folders, deleted db, everything and retried each time wit pull from 8pm UTC and it was able to complete the job once I allocated 12GB to the VM.  Could there be a mem leak someplace?

**Comment by n8herring** [comment]
it could never get past the 26th of 33 photos in the folder until I hit the 12GB mark and watching TOP it maxed at aprox 9GB used.

**Comment by n8herring** [comment]
After reaching the point where the scan job runs completely on a clean install there is still nothing showing in places.  All photos that have GPS information have the lat/lon populated in the database but there is nothing present in the geo json field ( just [} )...  just a thought here.  I wad seen someone posting about something working in another project called photoview.  When I read the instruction on that project it specifically mentioned to use the mapbox public key NOT a generated one. Not sure if the type of key makes a difference but thought it may be worth mentioning.

**Comment by VlikeBanana** [comment]
Anyone got an update on this? I also have the same issue.
I can search for places / locations but the album locations shows nothing on the map.

Mapbox working fine except for the Map feature.

**Comment by derneuere** [comment]
@VlikeBanana I think you should add your comment on this issue here instead:  https://github.com/LibrePhotos/librephotos/issues/535
